import { db } from '@/db';
import { events } from '@/db/schema';

async function main() {
    const sampleEvents = [
        {
            title: 'React Workshop: Building Modern Web Apps',
            description: 'Learn the fundamentals of React including hooks, state management, and component architecture. Perfect for developers looking to enhance their frontend skills.',
            venue: 'Tech Hub Conference Room',
            date: '2024-03-15',
            time: '14:00',
            bannerImageUrl: 'https://picsum.photos/800/400?random=1',
            maxAttendees: 30,
            organizerId: 1,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
            isActive: true,
        },
        {
            title: 'Annual Cultural Festival 2024',
            description: 'Celebrate diversity with traditional dances, music performances, and cultural exhibitions from around the world. Food stalls and art displays included.',
            venue: 'Main Auditorium',
            date: '2024-04-20',
            time: '10:00',
            bannerImageUrl: 'https://picsum.photos/800/400?random=2',
            maxAttendees: 200,
            organizerId: 2,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
            isActive: true,
        },
        {
            title: 'AI in Healthcare Seminar',
            description: 'Exploring the latest applications of artificial intelligence in medical diagnosis, treatment planning, and patient care management.',
            venue: 'Medical Center Auditorium',
            date: '2024-03-25',
            time: '09:30',
            bannerImageUrl: 'https://picsum.photos/800/400?random=3',
            maxAttendees: 80,
            organizerId: 3,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
            isActive: true,
        },
        {
            title: 'Basketball Championship Finals',
            description: 'The ultimate showdown between top college teams. Witness intense competition and athletic excellence in this championship match.',
            venue: 'Campus Stadium',
            date: '2024-03-30',
            time: '19:00',
            bannerImageUrl: 'https://picsum.photos/800/400?random=4',
            maxAttendees: 150,
            organizerId: 4,
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
            isActive: true,
        },
        {
            title: 'Weekend Hackathon: Innovation Challenge',
            description: '48-hour coding marathon where teams build innovative solutions to real-world problems. Prizes, mentorship, and networking opportunities.',
            venue: 'Innovation Lab',
            date: '2024-04-05',
            time: '18:00',
            bannerImageUrl: 'https://picsum.photos/800/400?random=5',
            maxAttendees: 60,
            organizerId: 5,
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
            isActive: true,
        },
        {
            title: 'Jazz Concert Night',
            description: 'An evening of smooth jazz featuring local and visiting musicians. Enjoy classic and contemporary jazz pieces in an intimate setting.',
            venue: 'Music Hall',
            date: '2024-03-22',
            time: '20:00',
            bannerImageUrl: 'https://picsum.photos/800/400?random=6',
            maxAttendees: 120,
            organizerId: 6,
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
            isActive: true,
        },
        {
            title: 'Modern Dance Competition',
            description: 'Contemporary dance competition showcasing innovative choreography and exceptional talent from dance schools across the region.',
            venue: 'Performing Arts Center',
            date: '2024-04-12',
            time: '16:00',
            bannerImageUrl: 'https://picsum.photos/800/400?random=7',
            maxAttendees: 100,
            organizerId: 7,
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
            isActive: true,
        },
        {
            title: 'Digital Art Exhibition: Future Visions',
            description: 'Immersive digital art showcase featuring interactive installations, VR experiences, and cutting-edge digital media artworks.',
            venue: 'Art Gallery',
            date: '2024-04-08',
            time: '11:00',
            bannerImageUrl: 'https://picsum.photos/800/400?random=8',
            maxAttendees: 75,
            organizerId: 8,
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
            isActive: true,
        },
        {
            title: 'Python Programming Bootcamp',
            description: 'Intensive 2-day Python programming course covering basics to advanced topics including web development with Django and data analysis.',
            venue: 'Computer Lab A',
            date: '2024-02-15',
            time: '09:00',
            maxAttendees: 25,
            organizerId: 1,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
            isActive: false,
        },
        {
            title: 'International Food Festival',
            description: 'Taste authentic cuisines from around the world. Local restaurants and cultural groups present traditional dishes and cooking demonstrations.',
            venue: 'Community Center',
            date: '2024-05-10',
            time: '12:00',
            bannerImageUrl: 'https://picsum.photos/800/400?random=9',
            maxAttendees: 180,
            organizerId: 2,
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
            isActive: true,
        },
        {
            title: 'Cybersecurity Workshop: Ethical Hacking',
            description: 'Learn ethical hacking techniques, penetration testing, and cybersecurity best practices. Hands-on labs and real-world scenarios included.',
            venue: 'Security Lab',
            date: '2024-03-28',
            time: '13:30',
            bannerImageUrl: 'https://picsum.photos/800/400?random=10',
            maxAttendees: 20,
            organizerId: 3,
            createdAt: new Date('2024-02-28').toISOString(),
            updatedAt: new Date('2024-02-28').toISOString(),
            isActive: true,
        },
        {
            title: 'Classical Music Symphony',
            description: 'Orchestra performance featuring masterpieces by Mozart, Beethoven, and Tchaikovsky. Experience the beauty of classical music live.',
            venue: 'Grand Concert Hall',
            date: '2024-04-18',
            time: '19:30',
            bannerImageUrl: 'https://picsum.photos/800/400?random=11',
            maxAttendees: 200,
            organizerId: 4,
            createdAt: new Date('2024-03-02').toISOString(),
            updatedAt: new Date('2024-03-02').toISOString(),
            isActive: true,
        },
        {
            title: 'Startup Pitch Competition',
            description: 'Emerging entrepreneurs present their innovative business ideas to a panel of investors and industry experts. Network with fellow entrepreneurs.',
            venue: 'Business Incubator',
            date: '2024-04-25',
            time: '15:00',
            bannerImageUrl: 'https://picsum.photos/800/400?random=12',
            maxAttendees: 90,
            organizerId: 5,
            createdAt: new Date('2024-03-10').toISOString(),
            updatedAt: new Date('2024-03-10').toISOString(),
            isActive: true,
        },
        {
            title: 'Photography Workshop: Street Photography',
            description: 'Master the art of street photography with professional techniques, composition tips, and post-processing skills. Bring your camera.',
            venue: 'Photography Studio',
            date: '2024-02-28',
            time: '10:30',
            maxAttendees: 15,
            organizerId: 6,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
            isActive: false,
        },
        {
            title: 'Tennis Tournament Championship',
            description: 'Annual tennis championship featuring singles and doubles matches. Open to all skill levels with separate brackets for beginners and advanced players.',
            venue: 'Tennis Courts Complex',
            date: '2024-04-14',
            time: '08:00',
            bannerImageUrl: 'https://picsum.photos/800/400?random=13',
            maxAttendees: 64,
            organizerId: 7,
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
            isActive: true,
        },
        {
            title: 'Mental Health Awareness Seminar',
            description: 'Important discussion on mental health challenges, coping strategies, and available resources. Expert speakers and support group sessions.',
            venue: 'Wellness Center',
            date: '2024-03-20',
            time: '14:30',
            bannerImageUrl: 'https://picsum.photos/800/400?random=14',
            maxAttendees: 50,
            organizerId: 8,
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
            isActive: true,
        },
        {
            title: 'Robotics Competition: Future Engineers',
            description: 'High school and college students showcase their robotic innovations in various challenges including autonomous navigation and problem-solving tasks.',
            venue: 'Engineering Lab',
            date: '2024-05-05',
            time: '11:30',
            bannerImageUrl: 'https://picsum.photos/800/400?random=15',
            maxAttendees: 80,
            organizerId: 1,
            createdAt: new Date('2024-03-08').toISOString(),
            updatedAt: new Date('2024-03-08').toISOString(),
            isActive: true,
        },
        {
            title: 'Creative Writing Workshop',
            description: 'Explore different writing genres, develop your unique voice, and receive feedback from published authors. Suitable for all experience levels.',
            venue: 'Library Conference Room',
            date: '2024-01-25',
            time: '16:30',
            maxAttendees: 20,
            organizerId: 2,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
            isActive: false,
        }
    ];

    await db.insert(events).values(sampleEvents);
    
    console.log('✅ Events seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});